#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


uv run python manage.py migrate
exec uv run python manage.py runserver_plus 0.0.0.0:443 --cert-file /certs/cert.pem --key-file /certs/key.pem
