volumes:
  knowledge_commons_profiles_local_postgres_data_backups: {}


services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
      args:
        ECR_REGISTRY: ${ECR_REGISTRY:-registry}
    image: knowledge_commons_profiles_local_django
    container_name: knowledge_commons_profiles_local_django
    volumes:
      - .:/app:z
      - ${HOME}/cert.pem:/certs/cert.pem:ro
      - ${HOME}/key.pem:/certs/key.pem:ro
    env_file:
      - ./.envs/.local/.django
    ports:
      - '443:443'
