services:
  docs:
    image: knowledge_commons_profiles_github_docs
    container_name: knowledge_commons_profiles_github_docs
    build:
      context: .
      dockerfile: ./compose/github/docs/Dockerfile
    env_file:
      - ./.envs/.github/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./knowledge_commons_profiles:/app/knowledge_commons_profiles:z
    ports:
      - '9000:9000'
    command: /start-docs
