volumes:
  production_traefik: {}

services:
  django:
    platform: linux/arm64
    build:
      platforms:
        - linux/arm64
      context: .
      dockerfile: ./compose/production/django/Dockerfile
      tags:
        - ${ECR_REGISTRY:-registry}/${ECR_REPOSITORY:-django}:${IMAGE_TAG:-latest}
        - ${ECR_REGISTRY:-registry}/${ECR_REPOSITORY:-django}:latest
        - knowledge_commons_profiles_production_django:${IMAGE_TAG:-latest}
        - knowledge_commons_profiles_production_django:latest
    image: knowledge_commons_profiles_production_django
    env_file:
      - ./.envs/.production/.django
    command: /start

  traefik:
    platform: linux/arm64
    build:
      platforms:
        - linux/arm64
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
      tags:
        - ${ECR_REGISTRY:-registry}/${ECR_REPOSITORY_TRAEFIK:-traefik}:${IMAGE_TAG:-latest}
        - ${ECR_REGISTRY:-registry}/${ECR_REPOSITORY_TRAEFIK:-traefik}:latest
        - knowledge_commons_profiles_production_traefik:${IMAGE_TAG:-latest}
        - knowledge_commons_profiles_production_traefik:latest
    image: knowledge_commons_profiles_production_traefik
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
    ports:
      - '0.0.0.0:80:80'
