# Generated by Django 5.1.4 on 2025-01-23 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0002_profile_memberships"),
    ]

    operations = []
