# Generated by Django 5.1.4 on 2025-02-04 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0003_wp_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cv_file",
            field=models.FileField(
                blank=True,
                help_text="Upload your CV (PDF format recommended)",
                null=True,
                upload_to="cvs/",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
