# Generated by Django 5.1.4 on 2025-02-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "newprofile",
            "0004_wpprofilefields_profile_cv_file_alter_profile_title_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="bluesky",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
