# Generated by Django 5.1.4 on 2025-02-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0005_profile_bluesky_alter_wppostsubtable_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_about_user",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_academic_interests",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_bio",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_cv",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_education",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_projects",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_publications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_talks",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_works",
            field=models.BooleanField(default=True),
        ),
    ]
