# Generated by Django 5.1.6 on 2025-02-10 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "newprofile",
            "0010_alter_profile_affiliation_alter_wppostsubtable_table",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="affiliation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="CoverImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
