# Generated by Django 5.0.12 on 2025-03-05 16:47

import knowledge_commons_profiles.newprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0013_alter_wppostsubtable_table_profileimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="WpBpActivity",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("component", models.CharField(max_length=75)),
                ("type", models.CharField(max_length=75)),
                ("action", models.TextField()),
                ("content", models.TextField()),
                ("primary_link", models.TextField()),
                ("item_id", models.BigIntegerField()),
                ("secondary_item_id", models.BigIntegerField(null=True)),
                ("date_recorded", models.DateTimeField()),
                ("hide_sitewide", models.BooleanField(default=False)),
                ("mptt_left", models.IntegerField(default=0)),
                ("mptt_right", models.IntegerField(default=0)),
                ("is_spam", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "wp_bp_activity",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WpBpActivityMeta",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("meta_key", models.CharField(max_length=255, null=True)),
                ("meta_value", models.TextField(null=True)),
            ],
            options={
                "db_table": "wp_bp_activity_meta",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WpBpFollow",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("follow_type", models.CharField(max_length=75)),
                ("date_recorded", models.DateTimeField()),
            ],
            options={
                "db_table": "wp_bp_follow",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WpBpNotification",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("item_id", models.BigIntegerField()),
                ("secondary_item_id", models.BigIntegerField(null=True)),
                ("component_name", models.CharField(max_length=75)),
                ("component_action", models.CharField(max_length=75)),
                ("date_notified", models.DateTimeField()),
                ("is_new", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "wp_bp_notifications",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WpBpUserBlogMeta",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("meta_key", models.CharField(max_length=255, null=True)),
                ("meta_value", models.TextField(null=True)),
            ],
            options={
                "db_table": "wp_bp_user_blogs_blogmeta",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WpTermRelationships",
            fields=[
                (
                    "object_id",
                    models.BigIntegerField(primary_key=True, serialize=False),
                ),
                ("term_order", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "wp_term_relationships",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="WpTermTaxonomy",
            fields=[
                (
                    "term_taxonomy_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("term_id", models.BigIntegerField()),
                ("taxonomy", models.CharField(max_length=32)),
                ("description", models.TextField()),
                ("parent", models.BigIntegerField(default=0)),
                ("count", models.BigIntegerField(default=0)),
            ],
            options={
                "db_table": "wp_term_taxonomy",
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="wpblog",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="wpbpgroup",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="wpbpgroupmember",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="wppost",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="wppostsubtable",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="wpprofiledata",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="wpprofilefields",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="wpuser",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="wpusermeta",
            options={"managed": False},
        ),
        migrations.AlterField(
            model_name="profile",
            name="about_user",
            field=knowledge_commons_profiles.newprofile.models.ProfileBleachField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=knowledge_commons_profiles.newprofile.models.ProfileBleachField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="publications",
            field=knowledge_commons_profiles.newprofile.models.ProfileBleachField(
                blank=True, null=True
            ),
        ),
    ]
