# Generated by Django 5.0.12 on 2025-03-05 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "newprofile",
            "0014_wpbpactivity_wpbpactivitymeta_wpbpfollow_and_more",
        ),
    ]

    operations = []
