# Generated by Django 5.0.12 on 2025-03-05 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0015_alter_wppostsubtable_table"),
    ]

    operations = []
