# Generated by Django 5.1.7 on 2025-04-01 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "newprofile",
            "0016_wpblog_wpbpactivity_wpbpactivitymeta_wpbpfollow_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_recent_activity",
            field=models.BooleanField(default=True),
        ),
    ]
