# Generated by Django 5.1.7 on 2025-04-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0018_profile_show_commons_sites"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="about_user",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="education",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="publications",
            field=models.TextField(blank=True, null=True),
        ),
    ]
