# Generated by Django 5.1.7 on 2025-04-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "newprofile",
            "0019_alter_profile_about_user_alter_profile_education_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="left_order",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="right_order",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
