# Generated by Django 5.1.8 on 2025-04-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0020_profile_left_order_profile_right_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="academic_interests",
            field=models.ManyToManyField(
                blank=True,
                related_name="profiles",
                to="newprofile.academicinterest",
            ),
        ),
    ]
