# Generated by Django 5.1.8 on 2025-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0021_alter_profile_academic_interests"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="works_order",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
