# Generated by Django 5.1.8 on 2025-04-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0022_profile_works_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="works_order",
            field=models.TextField(blank=True, null=True),
        ),
    ]
