# Generated by Django 5.1.8 on 2025-04-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0023_alter_profile_works_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="works_show",
            field=models.TextField(blank=True, null=True),
        ),
    ]
