# Generated by Django 5.1.8 on 2025-04-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0024_profile_works_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="works_work_show",
            field=models.TextField(blank=True, null=True),
        ),
    ]
