# Generated by Django 5.1.8 on 2025-04-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0025_profile_works_work_show"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="reference_style",
            field=models.CharField(
                blank=True, default="MHRA", max_length=255, null=True
            ),
        ),
    ]
