# Generated by Django 5.1.8 on 2025-04-12 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0026_profile_reference_style"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="reference_style",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ACM", "ACM"),
                    ("APA", "APA"),
                    ("APS", "APS"),
                    ("Chicago", "Chicago"),
                    ("Harvard", "Harvard"),
                    ("IEEE", "IEEE"),
                    ("JACS", "JACS"),
                    ("MHRA", "MHRA"),
                    ("MLA", "MLA"),
                    ("Vancouver", "Vancouver"),
                ],
                default="MHRA",
                max_length=255,
                null=True,
            ),
        ),
    ]
