# Generated by Django 5.1.8 on 2025-04-19 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0027_alter_profile_reference_style"),
    ]

    operations = [
        migrations.CreateModel(
            name="RORRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ror_id", models.URLField(blank=True, null=True)),
                ("institution_name", models.TextField(blank=True, null=True)),
                (
                    "grid_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["institution_name"],
                        name="newprofile__institu_4d2ab7_idx",
                    ),
                    models.Index(
                        fields=["ror_id"], name="newprofile__ror_id_fb0aa8_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="RORLookup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                (
                    "ror",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newprofile.rorrecord",
                    ),
                ),
            ],
        ),
    ]
