# Generated by Django 5.1.8 on 2025-04-19 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0028_rorrecord_rorlookup"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rorlookup",
            name="wp_user",
        ),
    ]
