# Generated by Django 5.1.8 on 2025-04-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0030_rorrecord_lat_rorrecord_lon"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rorlookup",
            index=models.Index(fields=["text"], name="idx_rorlookup_text"),
        ),
    ]
