# Generated by Django 5.1.8 on 2025-04-20 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newprofile", "0032_alter_rorlookup_ror"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_count", models.IntegerField()),
                ("user_count_active", models.IntegerField()),
                ("user_count_active_two", models.TextField()),
                ("user_count_active_three", models.TextField()),
                ("years", models.TextField()),
                ("data", models.TextField()),
                ("latlong", models.TextField()),
                ("topinsts", models.TextField()),
                ("topinstscount", models.TextField()),
                ("emails", models.TextField()),
                ("emailcount", models.TextField()),
            ],
        ),
    ]
