# Generated by Django 5.1.8 on 2025-05-15 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0033_userstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="WpBpGroupsGroupmeta",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("meta_key", models.CharField(max_length=255)),
                ("meta_value", models.TextField()),
            ],
            options={
                "db_table": "wp_bp_groups_groupmeta",
                "managed": False,
            },
        ),
    ]
