# Generated by Django 5.1.8 on 2025-05-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0034_wpbpgroupsgroupmeta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="profile",
            name="orcid",
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
