# Generated by Django 5.1.8 on 2025-05-23 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0035_alter_profile_email_alter_profile_orcid"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="external_sync_ids",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="in_membership_groups",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_member_of",
            field=models.TextField(blank=True, null=True),
        ),
    ]
