# Generated by Django 5.2.4 on 2025-10-29 13:45

import django.db.models.constraints
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0036_profile_external_sync_ids_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="COU",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "co",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cous",
                        to="newprofile.co",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="person_profile",
                        to="newprofile.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("affiliation", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("pending_approval", "Pending Approval"),
                            ("pending_confirmation", "Pending Confirmation"),
                            ("grace_period", "Grace Period"),
                            ("suspended", "Suspended"),
                            ("expired", "Expired"),
                            ("deleted", "Deleted"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("department", models.CharField(blank=True, max_length=255)),
                ("organization", models.CharField(blank=True, max_length=255)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_through", models.DateTimeField(blank=True, null=True)),
                (
                    "enrollment_flow",
                    models.CharField(
                        blank=True,
                        help_text="Name/key of the enrollment flow that created/last updated this role.",
                        max_length=255,
                    ),
                ),
                (
                    "source_system",
                    models.CharField(
                        blank=True,
                        help_text="Upstream system of record (e.g., HR, admissions, manual).",
                        max_length=255,
                    ),
                ),
                (
                    "source_reference",
                    models.CharField(
                        blank=True,
                        help_text="External identifier from the source system.",
                        max_length=255,
                    ),
                ),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "co",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="newprofile.co",
                    ),
                ),
                (
                    "cou",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles",
                        to="newprofile.cou",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="newprofile.person",
                    ),
                ),
                (
                    "sponsor",
                    models.ForeignKey(
                        blank=True,
                        help_text="Person who sponsors this role (if any).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sponsored_roles",
                        to="newprofile.person",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.AddIndex(
            model_name="cou",
            index=models.Index(
                fields=["co", "slug"], name="newprofile__co_id_628dc6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="cou",
            unique_together={("co", "slug")},
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["person", "co"], name="newprofile__person__cab0d8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["co", "cou"], name="newprofile__co_id_87d643_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["status"], name="newprofile__status_386e00_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["affiliation"], name="newprofile__affilia_0bce5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["valid_from", "valid_through"],
                name="newprofile__valid_f_456891_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(
                fields=["source_system", "source_reference"],
                name="newprofile__source__59a855_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="role",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=(
                    "person",
                    "co",
                    "cou",
                    "affiliation",
                    "status",
                    "source_system",
                    "source_reference",
                ),
                name="uniq_role_identity_status_source",
            ),
        ),
    ]
