# Generated by Django 5.2.4 on 2025-10-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "newprofile",
            "0037_co_cou_person_role_cou_newprofile__co_id_628dc6_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="co",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
