# Generated by Django 5.2.4 on 2025-10-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0038_alter_co_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="co",
            name="slug",
            field=models.SlugField(max_length=255),
        ),
    ]
