# Generated by Django 5.2.4 on 2025-10-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0039_alter_co_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="organization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
