# Generated by Django 5.2.4 on 2025-10-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0040_alter_role_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="person",
            name="email",
        ),
    ]
