# Generated by Django 5.2.4 on 2025-10-29 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0041_remove_person_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="source_reference",
            field=models.CharField(
                blank=True,
                help_text="External identifier from the source system.",
                max_length=255,
                null=True,
            ),
        ),
    ]
