# Generated by Django 5.2.4 on 2025-10-30 14:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0042_alter_role_source_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="emails",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=254),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
