# Generated by Django 5.2.4 on 2025-11-12 15:06

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0043_profile_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="role_overrides",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=254),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
