# Generated by Django 5.2.4 on 2025-11-12 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0044_profile_role_overrides"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_sync",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
