# Generated by Django 5.2.4 on 2025-11-14 13:05

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0045_profile_last_sync"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="profile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["emails"], name="profile_emails"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["role_overrides"], name="profile_role_overrides"
            ),
        ),
    ]
