# Generated by Django 5.2.8 on 2025-11-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0046_profile_profile_emails_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="cc_search_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
