# Generated by Django 6.0 on 2025-12-19 17:07

import knowledge_commons_profiles.newprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0047_profile_cc_search_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="cv_file",
            field=models.FileField(
                blank=True,
                help_text="Upload your CV (PDF format recommended)",
                null=True,
                upload_to=knowledge_commons_profiles.newprofile.models.cv_file_path,
            ),
        ),
    ]
