# Generated by Django 6.0.3 on 2026-03-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0048_alter_profile_cv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_memberships",
            field=models.BooleanField(default=True),
        ),
    ]
