# Generated by Django 6.0.3 on 2026-03-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0049_add_show_memberships"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_works_chart",
            field=models.BooleanField(default=True),
        ),
    ]
