# Generated by Django 6.0.3 on 2026-03-31 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0051_deduplicate_profile_usernames"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
