# Generated by Django 6.0.5 on 2026-06-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0056_username_citext"),
    ]

    operations = [
        migrations.CreateModel(
            name="WpTerm",
            fields=[
                (
                    "term_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "wp_terms",
                "managed": False,
            },
        ),
    ]
