# Generated by Django 6.0.5 on 2026-06-26 14:39

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0057_wpterm"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="central_user_id",
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
