# Generated by Django 6.0.5 on 2026-07-07 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0057_alter_profile_central_user_id"),
        ("newprofile", "0058_alter_profile_central_user_id"),
    ]

    operations = []
