# Generated by Django 6.0.7 on 2026-08-04 14:57

import django.db.models.deletion
import knowledge_commons_profiles.newprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0059_merge_central_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "alt_text",
                    models.TextField(
                        help_text="Accessible description used as the image alt text"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=knowledge_commons_profiles.newprofile.models.badge_image_path
                    ),
                ),
                ("order", models.IntegerField(db_index=True, default=0)),
            ],
            options={
                "ordering": ["order", "title"],
            },
        ),
        migrations.AddField(
            model_name="profile",
            name="show_badges",
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name="ProfileBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("awarded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newprofile.badge",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newprofile.profile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="badge",
            name="profiles",
            field=models.ManyToManyField(
                blank=True,
                related_name="badges",
                through="newprofile.ProfileBadge",
                to="newprofile.profile",
            ),
        ),
        migrations.AddConstraint(
            model_name="profilebadge",
            constraint=models.UniqueConstraint(
                fields=("badge", "profile"), name="unique_badge_per_profile"
            ),
        ),
    ]
