# Generated by Django 6.0.7 on 2026-09-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0061_seed_badges"),
    ]

    operations = [
        migrations.AddField(
            model_name="profilebadge",
            name="order",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
