# Generated by Django 5.1.8 on 2025-05-19 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cilogon", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TokenUserAgentAssociations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_agent", models.CharField(max_length=255)),
                ("token", models.TextField()),
                ("app", models.CharField(max_length=255)),
            ],
        ),
    ]
