# Generated by Django 5.1.8 on 2025-05-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cilogon", "0003_tokenuseragentassociations_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="tokenuseragentassociations",
            name="user_name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
