# Generated by Django 5.1.8 on 2025-05-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cilogon", "0004_tokenuseragentassociations_user_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tokenuseragentassociations",
            name="token",
        ),
        migrations.AddField(
            model_name="tokenuseragentassociations",
            name="access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tokenuseragentassociations",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
