# Generated by Django 5.1.8 on 2025-06-09 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cilogon", "0005_remove_tokenuseragentassociations_token_and_more"),
        ("newprofile", "0036_profile_external_sync_ids_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subassociation",
            options={
                "verbose_name": "CI Logon Association",
                "verbose_name_plural": "CI Logon Associations",
            },
        ),
        migrations.AlterField(
            model_name="subassociation",
            name="profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="newprofile.profile",
                verbose_name="Associated KC Profile",
            ),
        ),
        migrations.AlterField(
            model_name="subassociation",
            name="sub",
            field=models.CharField(max_length=255, verbose_name="CI Logon ID"),
        ),
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub", models.CharField(max_length=255)),
                ("secret_uuid", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newprofile.profile",
                    ),
                ),
            ],
        ),
    ]
