# Generated by Django 5.1.8 on 2025-07-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cilogon", "0006_alter_subassociation_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subassociation",
            name="sub",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="CI Logon ID"
            ),
        ),
    ]
