# Generated by Django 5.2.4 on 2025-11-10 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cilogon", "0007_alter_subassociation_sub"),
    ]

    operations = [
        migrations.AddField(
            model_name="subassociation",
            name="idp_name",
            field=models.TextField(
                blank=True, null=True, verbose_name="IDP Name"
            ),
        ),
    ]
