# Generated by Django 5.1

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("cilogon", "0010_emailverification_secret_uuid_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailverification",
            name="idp_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
