# Generated by Django 6.0.3 on 2026-05-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cilogon", "0011_emailverification_idp_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tokenuseragentassociations",
            index=models.Index(
                fields=["user_agent", "user_name", "app"],
                name="tua_ua_user_app_idx",
            ),
        ),
    ]
