# Generated by Django 6.0.5 on 2026-07-06 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cilogon", "0012_tokenuseragentassociations_tua_ua_user_app_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReservedUsername",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pattern",
                    models.CharField(
                        help_text='A username term to block. Matching ignores case, hyphens and underscores, and blocks any username that begins with the term (so "admin" blocks "admin123"). Use * as a wildcard for any characters, e.g. "*support*" to block the word anywhere.',
                        max_length=255,
                        unique=True,
                        verbose_name="Reserved term",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional note explaining why this term is reserved.",
                        max_length=255,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Untick to disable this term without deleting it.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reserved username",
                "verbose_name_plural": "Reserved usernames",
                "ordering": ["pattern"],
            },
        ),
    ]
