# Generated by Django 6.0.5 on 2026-07-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cilogon", "0014_seed_reserved_usernames"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceMode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Turn on to put the identity system into read-only maintenance mode: logins are blocked and profiles cannot be edited.",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="Login temporarily unavailable",
                        help_text="Heading shown on the maintenance page.",
                        max_length=300,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        default="<p>We are carrying out essential maintenance on the login system. You will not be able to sign in or edit your profile for a short while. Please try again later.</p>",
                        help_text="HTML body shown on the maintenance page.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Maintenance mode",
                "verbose_name_plural": "Maintenance mode",
            },
        ),
    ]
