#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Starting website monitor..."
echo "Check interval: ${CHECK_INTERVAL:-60} seconds"

cd /app

# Run the monitor script
exec python -m cron.monitor_website "$@"
