#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

echo "Collecting static files"
python /app/manage.py collectstatic --noinput

echo "Running gunicorn..."
exec /usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --timeout 30 --chdir=/app
