# Generated by Django 5.1.4 on 2025-01-10 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("affiliation", models.CharField(max_length=255)),
                ("twitter", models.CharField(blank=True, max_length=255)),
                ("github", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("orcid", models.CharField(blank=True, max_length=255)),
                ("mastodon", models.CharField(blank=True, max_length=255)),
                ("profile_image", models.URLField(blank=True)),
                ("works_username", models.CharField(blank=True, max_length=255)),
                ("about_user", models.TextField(blank=True, null=True)),
                ("education", models.TextField(blank=True, null=True)),
                (
                    "academic_interests",
                    models.ManyToManyField(
                        related_name="profiles", to="newprofile.academicinterest"
                    ),
                ),
            ],
        ),
    ]
