# Generated by Django 5.1.4 on 2025-01-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AcademicInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("username", models.CharField(db_index=True, max_length=255)),
                ("central_user_id", models.IntegerField(db_index=True, null=True)),
                ("affiliation", models.CharField(max_length=255)),
                ("twitter", models.CharField(blank=True, max_length=255)),
                ("github", models.CharField(blank=True, max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("orcid", models.CharField(blank=True, max_length=255)),
                ("mastodon", models.CharField(blank=True, max_length=255)),
                ("profile_image", models.URLField(blank=True)),
                ("works_username", models.CharField(blank=True, max_length=255)),
                ("about_user", models.TextField(blank=True, null=True)),
                ("education", models.TextField(blank=True, null=True)),
                ("upcoming_talks", models.TextField(blank=True, null=True)),
                ("projects", models.TextField(blank=True, null=True)),
                ("publications", models.TextField(blank=True, null=True)),
                ("site", models.TextField(blank=True, null=True)),
                (
                    "institutional_or_other_affiliation",
                    models.TextField(blank=True, null=True),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("figshare_url", models.TextField(blank=True, null=True)),
                ("commons_groups", models.TextField(blank=True, null=True)),
                ("recent_commons_activity", models.TextField(blank=True, null=True)),
                ("commons_sites", models.TextField(blank=True, null=True)),
                ("blog_posts", models.TextField(blank=True, null=True)),
                ("cv", models.TextField(blank=True, null=True)),
                ("facebook", models.TextField(blank=True, null=True)),
                ("linkedin", models.TextField(blank=True, null=True)),
                ("website", models.TextField(blank=True, null=True)),
                (
                    "academic_interests",
                    models.ManyToManyField(
                        related_name="profiles", to="newprofile.academicinterest"
                    ),
                ),
            ],
        ),
    ]
