# Generated by Django 5.1.4 on 2025-01-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="central_user_id",
            field=models.IntegerField(db_index=True, default=123),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="profile",
            name="username",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
