# Generated by Django 5.1.4 on 2025-01-22 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0002_profile_central_user_id_alter_profile_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="blog_posts",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="commons_groups",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="commons_sites",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="cv",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="facebook",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="figshare_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="institutional_or_other_affiliation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="linkedin",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="projects",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="publications",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="recent_commons_activity",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="site",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="upcoming_talks",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="website",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name="profile",
            name="academic_interests",
        ),
        migrations.AlterField(
            model_name="profile",
            name="title",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="academic_interests",
            field=models.TextField(blank=True, null=True),
        ),
    ]
