# Generated by Django 5.1.4 on 2025-01-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0003_profile_blog_posts_profile_commons_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="central_user_id",
            field=models.IntegerField(db_index=True, null=True),
        ),
    ]
