# Generated by Django 5.1.4 on 2025-01-22 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0004_alter_profile_central_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="academic_interests",
        ),
        migrations.AddField(
            model_name="profile",
            name="academic_interests",
            field=models.ManyToManyField(
                related_name="profiles", to="newprofile.academicinterest"
            ),
        ),
    ]
