# Generated by Django 5.1.4 on 2025-02-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newprofile", "0009_alter_academicinterest_text_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="affiliation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
