# Generated by Django 5.1.6 on 2025-02-10 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "newprofile",
            "0010_alter_profile_affiliation_alter_wppostsubtable_table",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="affiliation",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="CoverImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newprofile.wpuser",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WpBpGroup",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("slug", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("hidden", "Hidden"),
                        ],
                        db_index=True,
                        default="public",
                        max_length=10,
                    ),
                ),
                ("enable_forum", models.BooleanField(default=True)),
                ("date_created", models.DateTimeField()),
                (
                    "parent_id",
                    models.BigIntegerField(db_index=True, default=0),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        db_column="creator_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newprofile.wpuser",
                    ),
                ),
            ],
            options={
                "db_table": "wp_bp_groups",
            },
        ),
        migrations.CreateModel(
            name="WpBpGroupMember",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("inviter_id", models.BigIntegerField(db_index=True)),
                (
                    "is_admin",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("is_mod", models.BooleanField(db_index=True, default=False)),
                ("user_title", models.CharField(max_length=100)),
                ("date_modified", models.DateTimeField()),
                ("comments", models.TextField()),
                (
                    "is_confirmed",
                    models.BooleanField(db_index=True, default=False),
                ),
                ("is_banned", models.BooleanField(default=False)),
                ("invite_sent", models.BooleanField(default=False)),
                (
                    "group",
                    models.ForeignKey(
                        db_column="group_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newprofile.wpbpgroup",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_memberships",
                        to="newprofile.wpuser",
                    ),
                ),
            ],
            options={
                "db_table": "wp_bp_groups_members",
            },
        ),
        migrations.CreateModel(
            name="WpUserMeta",
            fields=[
                (
                    "umeta_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "meta_key",
                    models.CharField(db_index=True, max_length=255, null=True),
                ),
                ("meta_value", models.TextField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="newprofile.wpuser",
                    ),
                ),
            ],
            options={
                "db_table": "wp_usermeta",
            },
        ),
        migrations.AddIndex(
            model_name="wpbpgroup",
            index=models.Index(
                fields=["creator_id"], name="wp_bp_group_creator_41b261_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wpbpgroup",
            index=models.Index(
                fields=["status"], name="wp_bp_group_status_93aba8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wpbpgroup",
            index=models.Index(
                fields=["parent_id"], name="wp_bp_group_parent__030b85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wpbpgroupmember",
            index=models.Index(
                fields=["group_id"], name="wp_bp_group_group_i_046440_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wpbpgroupmember",
            index=models.Index(
                fields=["is_admin"], name="wp_bp_group_is_admi_6f8c72_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wpbpgroupmember",
            index=models.Index(
                fields=["is_mod"], name="wp_bp_group_is_mod_a93c31_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wpbpgroupmember",
            index=models.Index(
                fields=["user_id"], name="wp_bp_group_user_id_bc6a62_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wpbpgroupmember",
            index=models.Index(
                fields=["inviter_id"], name="wp_bp_group_inviter_11dd5c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wpbpgroupmember",
            index=models.Index(
                fields=["is_confirmed"], name="wp_bp_group_is_conf_666966_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wpusermeta",
            index=models.Index(fields=["meta_key"], name="meta_key_idx"),
        ),
    ]
