name: deploy-dev

on:
  workflow_run:
    workflows: ["CI"]
    branches: [dev]
    types:
      - completed

env:
  AWS_REGION: us-east-1                       # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: kcprofiles-dev              # set this to your Amazon ECR repository name
  ECR_REPOSITORY_TRAEFIK: kcprofiles-traefik-dev
  ECR_REPOSITORY_POSTGRES: kcprofiles-postgres-dev
  ECR_REPOSITORY_REDIS: kcprofiles-redis-dev
  ECS_SERVICE: kcprofiles-dev-blue            # set this to your Amazon ECS service name
  ECS_CLUSTER: kcprofiles-dev                 # set this to your Amazon ECS cluster name

jobs:
  deploy-packages:
    name: Deploy-Dev
    runs-on: ubuntu-24.04-arm
    environment: dev
    # only run if the test workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: dev

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@ececac1a45f3b08a01d2dd070d28d111c5fe6722
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@62f4f872db3836360b72999f4b87f1ff13310f3a

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          # Build a docker container and
          # push it to ECR so that it can
          # be deployed to ECS.
          docker compose -f docker-compose.dev.yml build

          # push the Django repository
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

          # push the Traefik repository
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_TRAEFIK:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_TRAEFIK:latest

          # push the Postgres repository
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_POSTGRES:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_POSTGRES:latest

          # register env variables
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY_TRAEFIK:$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Force deployment
        run: |
          aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE --force-new-deployment
